os:
  - linux
  - osx

sudo: required

script:
  - time ./download-po-util.sh ci
  - cd build-test
  - time ~/po-util.sh photon build
  - time ~/po-util.sh electron clean
  - time ~/po-util.sh electron build
