dist: trusty
sudo: required
language: bash
before_install:
  - sudo apt-get install -y expect
install:
  - ./config-expect.sh
  - ./po-util.sh install
script:
  - po photon build build-test/
  - po electron clean build-test/
  - po electron build build-test/
  - po P1 clean build-test/
  - po P1 build build-test/
  - po core clean build-test/
  - po core build build-test/
  - po duo clean build-test/
  - po duo build build-test/
